print("Exercise 9: Creating 4 word sentence from the back")
word1 = input("Enter 4th word: ")
word2 = input("Enter 3rd word: ")
word3 = input("Enter 2nd word: ")
word4 = input("Enter 1st word: ")
print(word4 + " " + word3 + " " + word2 + " " + word1)