print("Exercise 3: Mathematical formula: Area of Trapezoid")
a = float(input("Enter parameter A (length of parallel side): "))
c = float(input("Enter parameter C (length of parallel side): "))
v = float(input("Enter height: "))
area_trapezoid = float(((a+c)*v)/2)
print("The area of the given trapezoid is: " + str(area_trapezoid))
